name: Tyh Blog Github Actions

# 当 main 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        uses: actions/checkout@v3
        #安装npm
        with:
          npm-version: 10.x
      # 安装依赖项
      - name: Install
        run: npm i

      # 打包文档
      - name: Build
        run: npm run build

      # https://github.com/peaceiris/actions-gh-pages#readme
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
